feat: initial module
terraform-ibm-modules/terraform-ibm-db2-cloud pull request #4
Opened 2024-11-27 16:46 UTC by MatthewLemmond

### Description
Initial version of the module to create db2 instances

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Initial working release of the module for testing the DB2 resource instance creation

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-27 16:46 UTC, MatthewLemmond commented
/run pipeline

2024-11-27 16:55 UTC, MatthewLemmond commented
/run pipeline

2024-12-05 15:51 UTC, ocofaigh commented on .catalog-onboard-pipeline.yaml
> +    offering_id: 30a698d4-ab56-4668-bc01-03cd2135d7e4 MQ?
This is `90a14f92-4b86-4b27-acc1-dd6eefe0bfe9`

2024-12-13 14:10 UTC, shemau requested changes
Do we want both the basic and advanced example? The basic one does not have a readme.md if it is being kept.

2024-12-13 14:10 UTC, shemau commented on .catalog-onboard-pipeline.yaml
> +  - name: deploy-arch-ibm-mq-cloud
This will be my copy and paste error

2024-12-13 15:21 UTC, ocofaigh commented on version.tf
> +      version = ">= 1.72.1"
why did you remove the upper limit? Please add it back `">= 1.72.1, < 2.0.0"`

2024-12-13 15:22 UTC, ocofaigh commented on README.md
> +# DB2 project
can we have a better title?

2024-12-13 15:27 UTC, ocofaigh requested changes
The tests need to test the DA (standard and upgrade). Thats a big gap. Especially since the provider visibility is set to private. Your going to need to test this in schematics

2024-12-13 15:33 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 15:41 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 15:48 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 16:14 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 16:58 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 17:10 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 17:24 UTC, MatthewLemmond commented
/run pipeline

2024-12-13 18:43 UTC, ocofaigh approved these changes

2024-12-13 18:45 UTC, merged

2024-12-13 18:45 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-db2-cloud/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: